version: "3.9"
services:
  web:
    container_name: "MLABweb-web"
    build: .
    ports:
      - "8000:5000"
    networks:
      internal:
        ipv4_address: 172.10.0.10
    volumes:
      - "/home/roman/repos/mlab/MLABweb/src/MLABweb:/MLABweb"
      - "/data/mlab/mlab-modules:/data/mlab/mlab-modules"


  updater:
    container_name: MLABweb-updater
    build: repository_downloader/.
    volumes:
      - "/data/mlab/mlab-modules:/data/mlab/mlab-modules"
      - "/home/roman/repos/mlab/MLABweb/repository_downloader:/app"
    networks:
      internal:
        ipv4_address: 172.10.0.11

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      internal:
        ipv4_address: 172.10.0.14
    #volumes:
    #  - "/home/roman/repos/mlab/Modules:/data/mlab/Modules"
    #  - "/home/roman/repos/mlab-modules:/data/mlab/modules-org"


networks:
  internal:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
